package uk.ac.liv.csc.semanticweblab.modtool.events;

import java.util.EventObject;

/**
 * This event is generated by an {@link OutputEventGenerator}. The event is
 * passed to every {@link OutputEventListener} object that registered to receive
 * such events using the component's
 * {@link OutputEventGenerator#addOutputEventListener(OutputEventListener)}.
 * 
 * @author pdoran
 * 
 */
public class OutputEvent extends EventObject {
	private static final long serialVersionUID = 8876902057554253552L;
	/**
	 * The message that forms the OutputEvent.
	 */
	private String message;

	/**
	 * Constructs an OutputEvent object.
	 * 
	 * @param source
	 *            the object orginated the event.
	 * @param message
	 *            the message for this event.
	 */
	public OutputEvent(Object source, String message) {
		super(source);
		this.message = message;
	}

	/**
	 * Returns the message string associated with this action.
	 * 
	 * @return the message
	 */
	public String getMessage() {
		return this.message;
	}
}